services:
  - type: web
    name: glossary
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    apt:
      packages:
        - ffmpeg
        - libavcodec-extra